name: next_gen_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  async: ^2.13.0
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.3.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0


flutter:
  uses-material-design: true